version: "3.9"

services:
  db:
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_DB=prefect
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3